/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registravimas;

import Naudotojai.Pacientas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Martin
 */
public class Vizitai extends javax.swing.JFrame {

    
    String laikas = null;
    /**
     * Creates new form Vizitai
     */
    public Vizitai() {
        initComponents();
        ParuostiParodykVizitus();
        
        
    }
    
    private int AsmensKodas;
   
   public void setCurrentUserAsmensKodas (int asm)
   {
       AsmensKodas = asm;
       
      
   }
   
   private void ParuostiParodykVizitus() { //kadangi pirma yra paleidziamas visas kodas ir tik poto gaunamas asmens kodas reikia asmens koda gauti truputelis veliau
        
        new Timer(50, new ActionListener() {
            
             int i = 0;
            public void actionPerformed(ActionEvent ae) {
                i++;
                if (i == 1)
                { 
                    ParodykVizitus ();
                }   
            }
        }).start();
    }
    
    void ParodykVizitus ()
    {
        int asm = 0;
        
       try
    {
      // create our mysql database connection
      String myDriver = "org.apache.derby.jdbc.ClientDriver";
      String myUrl = "jdbc:derby://localhost:1527/Sveikatos Centras";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "sveikuoliai", "sveikuoliai");
      PreparedStatement ps = conn.prepareStatement ("SELECT GYDYTOJOASMKODAS, PRADINISLAIKAS FROM APP.VIZITAI WHERE PACIENTOASMKODAS = ?");
      PreparedStatement ps2 = conn.prepareStatement ("SELECT * FROM APP.NAUDOTOJAI WHERE ASMENSKODAS = ?");
      ps.setString(1,Integer.toString(AsmensKodas));
      ResultSet rs = ps.executeQuery();
    
    
      
      DefaultListModel listas = new DefaultListModel();
      
     
      while (rs.next())
      {    asm = rs.getInt("GYDYTOJOASMKODAS");
           laikas = rs.getString("PRADINISLAIKAS");
         
           
           
           ps2.setString(1,Integer.toString(asm));
           ResultSet rs2 = ps2.executeQuery();
      
          
          while (rs2.next())
              
         { 
            String text = rs2.getString("VARDAS") + "  " + rs2.getString("PAVARDE") + "  " + rs2.getString("SPECIALYBE")+ "  " + " Kabineto numeris: " + 
                    rs2.getString("KABINETONR") + "    " + laikas;
             
             listas.addElement(text);
             
          }
          rs2.close();
      }
         vizitai.setModel(listas);
      
      rs.close();
      
    
 
      
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
        
    }
    
    
    
    void AtsauktiVizita ()
    {
        
       String tekstas = vizitai.getSelectedValue();
         String[] itemai = tekstas.split("  ");
         
         try { 
            String url = "jdbc:derby://localhost:1527/Sveikatos Centras"; 
            Connection conn = DriverManager.getConnection(url,"sveikuoliai","sveikuoliai"); 
            String query = "delete from APP.VIZITAI where PRADINISLAIKAS = ? AND PACIENTOASMKODAS = ? ";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, itemai[5] );
            preparedStmt.setInt(2, AsmensKodas );
            preparedStmt.execute();
            JOptionPane.showMessageDialog(null,"Pavyko");
            ((DefaultListModel)vizitai.getModel()).clear();
            ParodykVizitus ();
            conn.close();
           
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Nepavyko", "Error", // if user does not enter name error windows pops up
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        } 
    }       
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atgal = new javax.swing.JButton();
        AtsauktiVizita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vizitai = new javax.swing.JList<>();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atgal.setText("Atgal");
        atgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atgalActionPerformed(evt);
            }
        });

        AtsauktiVizita.setText("Atšaukti");
        AtsauktiVizita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtsauktiVizitaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Vizitai");

        vizitai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(vizitai);

        refresh.setText("Atnaujinti");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 234, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AtsauktiVizita, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(389, 389, 389)
                .addComponent(atgal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(atgal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(AtsauktiVizita, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 143, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atgalActionPerformed
        Pacientas men = new Pacientas();
        men.setVisible(true);
        men.SetCurrentUserAsmensKodas(AsmensKodas);
        super.dispose();
    }//GEN-LAST:event_atgalActionPerformed

    private void AtsauktiVizitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtsauktiVizitaActionPerformed
      
        AtsauktiVizita ();  
        
    }//GEN-LAST:event_AtsauktiVizitaActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
         ((DefaultListModel)vizitai.getModel()).clear();
            ParodykVizitus ();
            
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vizitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vizitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vizitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vizitai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vizitai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtsauktiVizita;
    private javax.swing.JButton atgal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JList<String> vizitai;
    // End of variables declaration//GEN-END:variables
}
