/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Info;

import Naudotojai.Pacientas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Timer;

/**
 *
 * @author Martin
 */
public class SveikatosKnygute extends javax.swing.JFrame {

    /**
     * Creates new form SveikatosKnyg
     */
    public SveikatosKnygute() {
        initComponents();
        ParuostiRodymui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   private int AsmensKodas;
     
    public void SetCurrentUserAsmensKodas(int asm)
    { 
      
       AsmensKodas = asm; 
      
        
    }
    
    private void ParuostiRodymui() { //kadangi pirma yra paleidziamas visas kodas ir tik poto gaunamas asmens kodas reikia asmens koda gauti truputelis veliau
        
        new Timer(50, new ActionListener() {
            
             int i = 0;
            public void actionPerformed(ActionEvent ae) {
                i++;
                if (i == 1)
                { 
                    ParodykIrasus ();
                  
                
                }
                
            }
        }).start();
    }
    
    void ParodykIrasus ()
    {
        irasai.setText(null);
        irasai.setEditable(false);
        
         try { 
             
            String url = "jdbc:derby://localhost:1527/Sveikatos Centras"; 
            Connection conn = DriverManager.getConnection(url,"sveikuoliai","sveikuoliai");
            String query = "Select IRASAS, DATA from APP.SVEIKATOSKNYGELE where PACIENTOASM = ?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setInt(1,AsmensKodas);
            ResultSet rs = preparedStmt.executeQuery();
            
            while (rs.next())
            {
                
                irasai.append(rs.getString("DATA") +"  " + rs.getString("IRASAS") + "\n");
                
            }
            
           
            conn.close(); 
            
        } catch (Exception e) { 
           
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        }
        
        
        
    }
    
     
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        irasai = new javax.swing.JTextArea();
        Grizti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        irasai.setColumns(20);
        irasai.setRows(5);
        jScrollPane1.setViewportView(irasai);

        Grizti.setText("Atgal");
        Grizti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GriztiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Įrašai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(337, 337, 337)
                        .addComponent(Grizti, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grizti, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GriztiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GriztiActionPerformed
        Pacientas men = new Pacientas ();
        men.setVisible(true);
        men.SetCurrentUserAsmensKodas(AsmensKodas);
        super.dispose();
    }//GEN-LAST:event_GriztiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SveikatosKnygute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SveikatosKnygute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SveikatosKnygute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SveikatosKnygute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SveikatosKnygute().setVisible(true);
            }
        });
        
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Grizti;
    private javax.swing.JTextArea irasai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
