/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Naudotojai;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import SveikatosCentras.Login;

/**
 *
 * @author Martin
 */
public class Adminai extends javax.swing.JFrame {

    /**
     * Creates new form Adminai
     */
    public Adminai() {
        initComponents();
        rodykInfo ();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      
             
    private int  AsmensKodas, SveikatosDraud,  SocApsaugaNR;
    private String vardass, pavard, TekstasApieImokas;
    
     void UzregistruotiNaudotoja (boolean adminas, boolean daktar, String specialyb, String kabNR )
        {
         vardass = vardas.getText();
         pavard = pavarde.getText();
         AsmensKodas = Integer.parseInt (asmn.getText());
         SveikatosDraud = Integer.parseInt(SDN.getText());
         SocApsaugaNR = Integer.parseInt(SAN.getText());
         boolean admin = adminas;
         boolean daktaras = daktar;
         String specialybe = specialyb;
         String KabNr = kabNR;
       
        try { 
            String url = "jdbc:derby://localhost:1527/Sveikatos Centras"; 
            Connection conn = DriverManager.getConnection(url,"sveikuoliai","sveikuoliai"); 
            PreparedStatement ps = conn.prepareStatement("INSERT INTO APP.NAUDOTOJAI VALUES (?, ?,?,?,?,?,?,?,?)");
            ps.setInt(1, AsmensKodas);
            ps.setInt(2, SveikatosDraud);
            ps.setInt(3, SocApsaugaNR);
            ps.setString(4, vardass);
            ps.setString(5, pavard);
            ps.setBoolean (6, admin);
            ps.setBoolean (7, daktaras);
            ps.setString(8, specialybe);
            ps.setString(9, KabNr);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Pavyko");

            conn.close(); 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Nepavyko", "Error", // if user does not enter name error windows pops up
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        }
    }
    
       void PasalintiNaudotoja (int AsmensKodas, String vard, String pavard)
       {
          
        
         
       
        try { 
            String url = "jdbc:derby://localhost:1527/Sveikatos Centras"; 
            Connection conn = DriverManager.getConnection(url,"sveikuoliai","sveikuoliai"); 
            String query = "delete from APP.NAUDOTOJAI where ASMENSKODAS = ? AND VARDAS = ? AND PAVARDE = ?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setInt(1, AsmensKodas );
            preparedStmt.setString(2, vard );
            preparedStmt.setString(3, pavard );
            preparedStmt.execute();
            JOptionPane.showMessageDialog(null,"Pavyko");
            conn.close();
           

        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Nepavyko", "Error", // if user does not enter name error windows pops up
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        }
       }
   
       void AtnaujintiInfo (String text)
       {
           
           try { 
            String url = "jdbc:derby://localhost:1527/Sveikatos Centras"; 
            Connection conn = DriverManager.getConnection(url,"sveikuoliai","sveikuoliai"); 
            PreparedStatement ps = conn.prepareStatement("UPDATE APP.INFORMACIJA SET IMOKOS = ?");
            ps.setString(1,text);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Pavyko");

            conn.close(); 
        } catch (Exception e) { 
            
            JOptionPane.showMessageDialog(null, "Nepavyko", "Error", // if user does not enter name error windows pops up
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        }
           
       }
       
       void rodykInfo ()
       {
      try
    {
      // create our mysql database connection
      String myDriver = "org.apache.derby.jdbc.ClientDriver";
      String myUrl = "jdbc:derby://localhost:1527/Sveikatos Centras";
      Class.forName(myDriver);
      Connection conn = DriverManager.getConnection(myUrl, "sveikuoliai", "sveikuoliai");
      String query = "SELECT * FROM APP.INFORMACIJA";
      Statement st = conn.createStatement();
      ResultSet rs = st.executeQuery(query);
      while (rs.next())
      {
          text.setText(rs.getString("IMOKOS"));
      }
      st.close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception! ");
      System.err.println(e.getMessage());
    }
       }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasalintiDaktara = new javax.swing.JButton();
        PridetiDaktara = new javax.swing.JButton();
        PridetiPacienta = new javax.swing.JButton();
        PasalintiPacienta = new javax.swing.JButton();
        Iseiti = new javax.swing.JButton();
        vardas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pavarde = new javax.swing.JTextField();
        profesija = new javax.swing.JTextField();
        asmn = new javax.swing.JTextField();
        SDN = new javax.swing.JTextField();
        SAN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        AtnaujintiImokas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        KabinetoNR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PasalintiDaktara.setText("Pašalinti Daktarą");
        PasalintiDaktara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasalintiDaktaraActionPerformed(evt);
            }
        });

        PridetiDaktara.setText("Pridėti Daktarą");
        PridetiDaktara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridetiDaktaraActionPerformed(evt);
            }
        });

        PridetiPacienta.setText("Pridėti Pacientą");
        PridetiPacienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridetiPacientaActionPerformed(evt);
            }
        });

        PasalintiPacienta.setText("Pašalinti Pacientą");
        PasalintiPacienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasalintiPacientaActionPerformed(evt);
            }
        });

        Iseiti.setText("Išeiti");
        Iseiti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IseitiActionPerformed(evt);
            }
        });

        jLabel1.setText("Vardas:");

        asmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asmnActionPerformed(evt);
            }
        });

        jLabel2.setText("Pavardė:");

        jLabel3.setText("Profesija:");

        jLabel4.setText("Asmens Kodas:");

        jLabel5.setText("Sveikatos Dradimo Numeris:");

        jLabel6.setText("Socialinės Apsaugos Numeris:");

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        AtnaujintiImokas.setText("Atnaujinti informaciją");
        AtnaujintiImokas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtnaujintiImokasActionPerformed(evt);
            }
        });

        jLabel7.setText("Kabineto NR.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Iseiti, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasalintiPacienta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(AtnaujintiImokas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasalintiDaktara, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PridetiDaktara, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PridetiPacienta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SAN, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                .addComponent(asmn)
                                .addComponent(pavarde)
                                .addComponent(vardas)
                                .addComponent(profesija)
                                .addComponent(SDN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KabinetoNR, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasalintiDaktara, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PridetiDaktara, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(profesija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(KabinetoNR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PridetiPacienta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PasalintiPacienta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(Iseiti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AtnaujintiImokas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void asmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asmnActionPerformed

    private void PridetiPacientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridetiPacientaActionPerformed
        
        UzregistruotiNaudotoja (false, false, null, null);
        
    }//GEN-LAST:event_PridetiPacientaActionPerformed

    private void PridetiDaktaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridetiDaktaraActionPerformed
        String specialybe = profesija.getText();
        String KabNR = KabinetoNR.getText();
        UzregistruotiNaudotoja (false, true, specialybe, KabNR);
    }//GEN-LAST:event_PridetiDaktaraActionPerformed

    private void PasalintiDaktaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasalintiDaktaraActionPerformed
        int asmenskodas = Integer.parseInt(asmn.getText());
        vardass = vardas.getText();
         pavard = pavarde.getText();
       PasalintiNaudotoja (asmenskodas, vardass, pavard);
    }//GEN-LAST:event_PasalintiDaktaraActionPerformed

    private void PasalintiPacientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasalintiPacientaActionPerformed
         int asmenskodas = Integer.parseInt(asmn.getText());
        vardass = vardas.getText();
         pavard = pavarde.getText();
       PasalintiNaudotoja (asmenskodas, vardass, pavard);
    }//GEN-LAST:event_PasalintiPacientaActionPerformed

    private void IseitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IseitiActionPerformed
        Login log = new Login ();
        log.show();
        super.dispose();
    }//GEN-LAST:event_IseitiActionPerformed

    private void AtnaujintiImokasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtnaujintiImokasActionPerformed
        TekstasApieImokas = text.getText();
        AtnaujintiInfo (TekstasApieImokas);
    }//GEN-LAST:event_AtnaujintiImokasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtnaujintiImokas;
    private javax.swing.JButton Iseiti;
    private javax.swing.JTextField KabinetoNR;
    private javax.swing.JButton PasalintiDaktara;
    private javax.swing.JButton PasalintiPacienta;
    private javax.swing.JButton PridetiDaktara;
    private javax.swing.JButton PridetiPacienta;
    private javax.swing.JTextField SAN;
    private javax.swing.JTextField SDN;
    private javax.swing.JTextField asmn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pavarde;
    private javax.swing.JTextField profesija;
    private javax.swing.JTextArea text;
    private javax.swing.JTextField vardas;
    // End of variables declaration//GEN-END:variables
}
